name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: git archive -o deploy.zip HEAD

      - name: configure aws credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::761018890099:role/github-deployments
          aws-region: us-east-1
          output-credentials: true

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          application_name: chatbot-app
          environment_name: development
          version_label: ${{github.run_id}}
          region: us-east-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
